version: '3.1'

services:
  server:
    image: groundhog-server
    build:
      context: .
    ports:
      - '80:3000'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=groundhogs
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - groundhog-db:/var/lib/postgresql/data/pgdata

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 90:80
  #   volumes:
  #     - groundhog-pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - db

volumes:
  groundhog-db:
  # groundhog-pgadmin-data:
